config/routes.rb
News2Clone::Application.routes.draw do

  get "home/index"

  devise_for :users

  resources :users do
    resources :articles
    resources :categories
    resources :comments
    resources :votes
  end

  match "articles_by_max" => "home#articles_by_max"
  match "articles_by_min" => "home#articles_by_min"
  match "articles_by_date" => "home#articles_by_date"

  match "vote" => "home#vote"
  match "comment" => "articles#comment"
  
  root :to => "home#index"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article

  validates :description, :presence => true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!
  uses_tiny_mce

  # GET /comments
  # GET /comments.xml
  def index
    @comments = current_user.comments

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.xml
  def show
    @comment = current_user.comments.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.xml
  def new
    @comment = current_user.comments.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = current_user.comments.find(params[:id])
  end

  # POST /comments
  # POST /comments.xml
  def create
    @comment = current_user.comments.new(params[:comment])

    respond_to do |format|
      if @comment.save
        format.html { redirect_to(user_comment_path(current_user, @comment), :notice => 'Comment was successfully created.') }
        format.xml  { render :xml => @comment, :status => :created, :location => @comment }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.xml
  def update
    @comment = current_user.comments.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to(user_comment_path(current_user, @comment), :notice => 'Comment was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.xml
  def destroy
    @comment = current_user.comments.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to(user_comments_url) }
      format.xml  { head :ok }
    end
  end
end

app/views/comments/_comment.html.erb
<div class="comment">
  commented by <strong><%= link_to(comment.user.login, user_path(comment.user)) %></strong>
  at <strong><%= comment.created_at.strftime("%b'%e %Y %H:%M") %></strong><br />
  <p><%= comment.description %></p>
</div><br /><br />

app/views/comments/_form.html.erb
<%= form_for([current_user, @comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.select :article_id, options_from_collection_for_select(current_user.articles, "id", "title") %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :class => "mceEditor" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', edit_user_comment_path(current_user, @comment) %> |
<%= link_to 'Back', user_comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Article</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.article.title %></td>
    <td><%= comment.description %></td>
    <td><%= link_to 'Show', user_comment_path(current_user, comment) %></td>
    <td><%= link_to 'Edit', edit_user_comment_path(current_user, comment) %></td>
    <td><%= link_to 'Destroy', user_comment_path(current_user, comment), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_user_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', user_comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Article:</b>
  <%= @comment.article.title %>
</p>

<p>
  <b>Description:</b>
  <%= @comment.description %>
</p>


<%= link_to 'Edit', edit_user_comment_path(current_user, @comment) %> |
<%= link_to 'Back', user_comments_path %>