config/routes.rb
News2Clone::Application.routes.draw do

  get "home/index"

  devise_for :users

  resources :users do
    resources :articles
    resources :categories
    resources :comments
    resources :votes
  end

  match "articles_by_max" => "home#articles_by_max"
  match "articles_by_min" => "home#articles_by_min"
  match "articles_by_date" => "home#articles_by_date"

  match "vote" => "home#vote"
  match "comment" => "articles#comment"
  
  root :to => "home#index"
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  has_many :votes
  has_many :comments

  validates :title, :description, :presence => true
  validates_uniqueness_of :title
  validates_length_of :title, :in => 5..150

  scope :recent, Article.order("created_at")

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :authenticate_user!
  uses_tiny_mce

  # GET /articles
  # GET /articles.xml
  def index
    @articles = current_user.articles
  
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.xml
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.xml
  def new
    @article = current_user.articles.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = current_user.articles.find(params[:id])
    @category = @article.category
  end

  # POST /articles
  # POST /articles.xml
  def create
    @article = current_user.articles.new(params[:article])




    respond_to do |format|
      if @article.save
        format.html { redirect_to(user_article_path(current_user, @article), :notice => 'Article was successfully created.') }
        format.xml  { render :xml => @article, :status => :created, :location => @article }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.xml
  def update
    @article = current_user.articles.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to(user_article_path(current_user, @article), :notice => 'Article was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @article.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.xml
  def destroy
    @article = current_user.articles.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to(user_articles_url) }
      format.xml  { head :ok }
    end
  end

  def comment
    if params[:user_id].present? && params[:article_id].present?
      commenter = User.find(params[:user_id])
      article = Article.find(params[:article_id])
      if commenter.present? && article.present?
        commenter.comments.create(:article_id => article.id, :description => params[:description])
        @comments = article.comments
      end
    else
      @error = true
    end

    response do
      format.js
    end
  end
end

app/views/articles/_article.html.erb
<div class="article" id="<%= article.id %>">
  <h2><%= link_to(article.title, user_article_path(article.user, article)) %></h2>
  posted by <strong><%= link_to(article.user.login, user_path(article.user)) %></strong>
  at <strong><%= article.created_at.strftime("%b'%e %Y %H:%M") %></strong><br />
  <p><%= truncate(article.description, :length => 550) %></p>
  <strong class="votes_for"><%= article.votes.for.count %></strong> <%= link_to("Vote on Article", "javascript: void(0);", :class => 'vote_on') %> |
  <strong class="votes_against"><%= article.votes.against.count %></strong> <%= link_to("Vote against Article", "javascript: void(0);", :class => 'vote_against') %> |
  <strong class="comments"><%= article.comments.count %></strong> <%= link_to("Comment on Article", user_article_path(article.user, article)) %><br /><br />
</div>

app/views/articles/_form.html.erb
<%= form_for([current_user, @article]) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.select :category_id, options_from_collection_for_select(current_user.categories, "id", "title") %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :class => "mceEditor" %>
  </div>
  <div class="field">
    <%= f.label :source %><br />
    <%= f.text_field :source %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/comment.js.erb
<% if @error.present? %>
  alert('Возникли проблемы при добавлении Вашего комментария, попробуйте снова!');
<% else %>
  $("div.comments_list").html("<%= escape_javascript(render(@comments)) %>");
  $(".comments_counter").html("<%= @comments.count %>");
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', user_article_path(current_user, @article) %> |
<%= link_to 'Back', user_articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <tr>
    <th>Category</th>
    <th>Title</th>
    <th>Description</th>
    <th>Source</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @articles.each do |article| %>
  <tr>
    <td><%= article.category.title %></td>
    <td><%= article.title %></td>
    <td><%= article.description %></td>
    <td><%= article.source %></td>
    <td><%= link_to 'Show', user_article_path(current_user, article) %></td>
    <td><%= link_to 'Edit', edit_user_article_path(current_user, article) %></td>
    <td><%= link_to 'Destroy', user_article_path(current_user, article), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Article', new_user_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', user_articles_path %>

app/views/articles/show.html.erb
<script type="text/javascript">

$(function() {
  $('.comment_description').hide();

  $('.submit_comment').click(function() {
    var comment_block = $('.comment_description');
    if(comment_block.css('display') == 'none'){
      $('.comment_description').fadeIn(1000);
    }else{
      var article = $('.article_id').attr('id');
      var comment = $('.comment_description #description').val();
      $.post("<%= comment_path %>", { user_id : "<%= current_user.id %>", article_id : article, description : comment } );
      $('.comment_description').fadeOut(1000);
    }
  });
});

</script>

<h3 class="article_id" id="<%= @article.id %>">New </h3>

<p id="notice"><%= notice %></p>

<p>
  <b>Category:</b>
  <%= @article.category.title %>
</p>

<p>
  <b>Title:</b>
  <%= @article.title %>
</p>

<p>
  <b>Description:</b>
  <%= @article.description %>
</p>

<p>
  <b>Source:</b>
  <%= @article.source %>
</p>

<h3><strong class="comments_counter"><%= @article.comments.count %></strong> Comments: </h3>

<div class="new_comment">
  <div class="comment_description">
    <%= text_area_tag 'description', nil, :rows => 7, :cols => 100 %><br /><br />
  </div>
  <strong><%= link_to("Add comment", "javascript: void(0);", :class => 'submit_comment') %></strong>
</div><br /><br />

<div class="comments_list">
  <% if @article.comments.present? %>
    <% @article.comments.each do |comment| %>
     <div class="comment">
       commented by <strong><%= link_to(comment.user.login, user_path(comment.user)) %></strong>
       at <strong><%= comment.created_at.strftime("%b'%e %Y %H:%M") %></strong><br />
       <p><%= comment.description %></p>
     </div><br /><br />
    <% end %>
  <% end %>
</div>

<% if @article.user == current_user %>
  <%= link_to 'Edit', edit_user_article_path(current_user, @article) %> |
  <%= link_to 'Back', user_articles_path %>
<% end %><br />

<%= link_to 'Go back to all news', root_path %><br /><br />