config/routes.rb
News2Clone::Application.routes.draw do

  get "home/index"

  devise_for :users

  resources :users do
    resources :articles
    resources :categories
    resources :comments
    resources :votes
  end

  match "articles_by_max" => "home#articles_by_max"
  match "articles_by_min" => "home#articles_by_min"
  match "articles_by_date" => "home#articles_by_date"

  match "vote" => "home#vote"
  match "comment" => "articles#comment"
  
  root :to => "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @articles = Article.recent.page(params[:page]).per(3)

    @search = Article.search(params[:search])
  # @articles = @search.all

  end

     def vote
    if params[:user_id].present? && params[:article_id].present?
      voter = User.find(params[:user_id])
      article = Article.find(params[:article_id])
      if voter.present? && article.present?
        if voter.votes.where(:article_id => article.id).present?
          @voted = true
        else
          voter.votes.create(:article_id => article.id, :result => params[:result])
          if params[:result] == 'for'
            @votes_for = voter.votes.for.where(:article_id => article.id).count
          elsif params[:result] == 'against'
            @votes_against = voter.votes.against.where(:article_id => article.id).count
          end
        end
      end
    else
      @error = true
    end

    response do
      format.js
    end
  end



  def articles_by_max
    @articles = Article.all.sort {|a,b| b.votes.count <=> a.votes.count }

    response do
      format.js
    end
  end

  def articles_by_min
    @articles = Article.all.sort {|a,b| a.votes.count <=> b.votes.count }

    response do
      format.js
    end
  end

  def articles_by_date
    @articles = Article.recent.page(params[:page]).per(3)

    response do
      format.js
    end
  end


end


 

app/views/home/articles_by_date.js.erb
$('div.articles_list').html("<%= escape_javascript(render(@articles)) %>");

app/views/home/articles_by_max.js.erb
$('div.articles_list').html("<%= escape_javascript(render(@articles)) %>");

app/views/home/articles_by_min.js.erb
$('div.articles_list').html("<%= escape_javascript(render(@articles)) %>");

app/views/home/index.html.erb
<script type="text/javascript">

$(function() {
  $('.max_on').live("click", function(e) {
    $.get("<%= articles_by_max_path %>");
     e.preventDefault();
  });

  $('.min_on').live("click", function(e) {
    $.get("<%= articles_by_min_path %>");
     e.preventDefault();
  });

  $('.date_on').live("click", function(e) {
    $.get("<%= articles_by_date_path %>");
     e.preventDefault();
  });
  
  $('.vote_on').live("click", function(e) {
    var id = $(this).parents('.article').attr('id');
    $.post("<%= vote_path %>", { user_id : "<%= current_user.id %>", article_id : id, result : 'for' } );
   e.preventDefault();
  });
  $('.vote_against').live("click", function(e) {
    var id = $(this).parents('.article').attr('id');
    $.post("<%= vote_path %>", { user_id : "<%= current_user.id %>", article_id : id, result : 'against' } );
   e.preventDefault();
  });
});

</script>

<h1><strong>News</strong></h1>


  <%= form_for @search, :url => home_index_path, :html => {:method => :get} do |f| %>
    <%= f.label :title_contains %>
    <%= f.text_field :title_contains %><br />
   <br />
    <%= f.submit %>
  <% end %>

 
<br />

<% if @articles.present? %>
 <%= link_to 'Add new Article', new_user_article_path(current_user.id)%>|
 <%= link_to("Get last news", "javascript: void(0);", :class => 'date_on') %>
 <%= link_to("Sort by max rating", "javascript: void(0);", :class => 'max_on') %>
 <%=link_to("Sort by min rating", "javascript: void(0);", :class => 'min_on') %>
<% end %>
<br /><br />

<%= paginate @articles %>
<div style="clear:both"></div><br />

<div class="articles_list">
<% @articles.each do |article| %>
  <%= render @articles %>
<% end %>
</div><br /><br/><br />

<%= paginate @articles %>
<div style="clear:both"></div><br/><br />

app/views/home/vote.js.erb
<% if @error.present? %>
  alert('Возникли проблемы при Вашем голосовании, попробуйте снова!');
<% elsif @voted.present? %>
  alert('Вы уже проголосовали за эту новость!');
<% else %>
  var id = "<%= params[:article_id] %>";
  <% if @votes_for.present? %>
    $('#' + id + ' .votes_for').text("<%= @votes_for %>");
  <% elsif @votes_against.present? %>
    $('#' + id + ' .votes_against').text("<%= @votes_against %>");
  <% end %>
<% end %>