config/routes.rb
News2Clone::Application.routes.draw do

  get "home/index"

  devise_for :users

  resources :users do
    resources :articles
    resources :categories
    resources :comments
    resources :votes
  end

  match "articles_by_max" => "home#articles_by_max"
  match "articles_by_min" => "home#articles_by_min"
  match "articles_by_date" => "home#articles_by_date"

  match "vote" => "home#vote"
  match "comment" => "articles#comment"
  
  root :to => "home#index"
end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :user
  has_many :articles

  validates :title, :presence => true
  validates_uniqueness_of :title
  validates_length_of :title, :in => 3..30
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :authenticate_user!
  
  # GET /categories
  # GET /categories.xml
  def index
    @categories = current_user.categories

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.xml
  def show
    @category = current_user.categories.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.xml
  def new
    @user = current_user
    @category = current_user.categories.new(:user_id => current_user.id)

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = current_user.categories.find(params[:id])
  end

  # POST /categories
  # POST /categories.xml
  def create
    @category = current_user.categories.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to(user_category_path(current_user, @category), :notice => 'Category was successfully created.') }
        format.xml  { render :xml => @category, :status => :created, :location => @category }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.xml
  def update
    @category = current_user.categories.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to(user_category_path(@category), :notice => 'Category was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.xml
  def destroy
    @category = current_user.categories.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to(user_categories_url) }
      format.xml  { head :ok }
    end
  end
end

app/views/categories/_form.html.erb
<%= form_for([current_user, @category]) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', user_category_path(@category) %> |
<%= link_to 'Back', user_category_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.title %></td>
    <td><%= link_to 'Show', user_category_path(current_user, category) %></td>
    <td><%= link_to 'Edit', edit_user_category_path(current_user, category) %></td>
    <td><%= link_to 'Destroy', user_category_path(current_user,category), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_user_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', user_categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @category.title %>
</p>


<%= link_to 'Edit', edit_user_category_path(current_user, @category) %> |
<%= link_to 'Back', user_categories_path %>